// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

type Vault struct {
	ID            int64
	UserID        int64
	EncryptedBlob string
	UpdatedAt     sql.NullTime
}
