// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type PendingLogin struct {
	ID          string
	UserID      int64
	ServerState []byte
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type PendingRegistration struct {
	ID                 string
	Username           string
	UsernameNormalized string
	ServerState        []byte
	ExpiresAt          time.Time
	CreatedAt          time.Time
}

type User struct {
	ID                       int64
	Username                 string
	UsernameNormalized       string
	OpaqueRegistrationRecord []byte
	CryptoPolicyVersion      int64
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type Vault struct {
	ID            int64
	UserID        int64
	EncryptedBlob []byte
	Revision      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
