// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    sql.NullTime
}

type Vault struct {
	ID            int64
	UserID        int64
	EncryptedBlob string
	Revision      int64
	UpdatedAt     sql.NullTime
}
