// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    user_id,
    token_hash,
    expires_at
) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
}

// Creates a new session for a user allowing vault access.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username, 
    password_hash
) VALUES (?, ?)
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

// :exec tells sqlc this query modifies the database but doesn't return any rows.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.PasswordHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = ?
`

// Deletes a session by its corresponding token hash.
func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :exec
SELECT user_id
FROM sessions
WHERE token_hash = ?
AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

// Retrives a session by its corresponding token hash.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, getSessionByTokenHash, tokenHash)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, password_hash 
FROM users 
WHERE username = ? 
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           int64
	PasswordHash string
}

// :one tells sqlc to expect exactly one row and scan it directly into a struct.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getVaultByUserID = `-- name: GetVaultByUserID :one
SELECT encrypted_blob 
FROM vaults 
WHERE user_id = ? 
LIMIT 1
`

// Fetches just the encrypted string blob for a specific user ID.
func (q *Queries) GetVaultByUserID(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getVaultByUserID, userID)
	var encrypted_blob string
	err := row.Scan(&encrypted_blob)
	return encrypted_blob, err
}

const saveVault = `-- name: SaveVault :exec
INSERT INTO vaults (
    user_id, 
    encrypted_blob
) VALUES (?, ?)
ON CONFLICT(user_id) DO UPDATE SET 
    encrypted_blob = excluded.encrypted_blob, 
    updated_at = CURRENT_TIMESTAMP
`

type SaveVaultParams struct {
	UserID        int64
	EncryptedBlob string
}

// This handles the upsert logic. If a vault for the user exists, overwrite it; otherwise, create it.
func (q *Queries) SaveVault(ctx context.Context, arg SaveVaultParams) error {
	_, err := q.db.ExecContext(ctx, saveVault, arg.UserID, arg.EncryptedBlob)
	return err
}
