// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    user_id,
    token_hash,
    expires_at
) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
}

// CreateSession creates a new active session for a user, mapping their user ID to a hashed session token with an expiration timestamp.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username, 
    password_hash
) VALUES (?, ?)
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

// CreateUser registers a new user in the system with a unique username and a hashed password.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.PasswordHash)
	return err
}

const createVault = `-- name: CreateVault :exec
INSERT INTO vaults (
    user_id,
    encrypted_blob
) VALUES (?, ?)
`

type CreateVaultParams struct {
	UserID        int64
	EncryptedBlob string
}

// CreateVault initializes a new encrypted storage vault for a specific user.
func (q *Queries) CreateVault(ctx context.Context, arg CreateVaultParams) error {
	_, err := q.db.ExecContext(ctx, createVault, arg.UserID, arg.EncryptedBlob)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = ?
`

// DeleteSessionByTokenHash permanently removes a session by its token hash. Typically invoked during user logout.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT user_id
FROM sessions
WHERE token_hash = ?
AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

// GetSessionByTokenHash retrieves the user ID associated with a session token, provided the session has not expired yet.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash
FROM users
WHERE username = ?
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
}

// GetUserByUsername retrieves a user's ID, username, and password hash by their username.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getVaultByUserID = `-- name: GetVaultByUserID :one
SELECT encrypted_blob, revision, updated_at
FROM vaults
WHERE user_id = ?
LIMIT 1
`

type GetVaultByUserIDRow struct {
	EncryptedBlob string
	Revision      int64
	UpdatedAt     sql.NullTime
}

// GetVaultByUserID fetches the encrypted data blob, current revision number, and last update timestamp for a user's vault.
func (q *Queries) GetVaultByUserID(ctx context.Context, userID int64) (GetVaultByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultByUserID, userID)
	var i GetVaultByUserIDRow
	err := row.Scan(&i.EncryptedBlob, &i.Revision, &i.UpdatedAt)
	return i, err
}

const updateVaultIfRevisionMatches = `-- name: UpdateVaultIfRevisionMatches :execrows
UPDATE vaults
SET 
    encrypted_blob = ?,
    revision = revision + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
AND revision = ?
`

type UpdateVaultIfRevisionMatchesParams struct {
	EncryptedBlob string
	UserID        int64
	Revision      int64
}

// UpdateVaultIfRevisionMatches implements optimistic concurrency control to update a user's vault.
// It increments the vault revision and updates the blob only if the provided revision matches the current state in the database.
// Returns the number of affected rows (0 means a conflict occurred and the update failed).
func (q *Queries) UpdateVaultIfRevisionMatches(ctx context.Context, arg UpdateVaultIfRevisionMatchesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVaultIfRevisionMatches, arg.EncryptedBlob, arg.UserID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
