// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createPendingLogin = `-- name: CreatePendingLogin :exec
INSERT INTO pending_logins (
	id,
	user_id,
	server_state,
	expires_at
) VALUES (?, ?, ?, ?)
`

type CreatePendingLoginParams struct {
	ID          string
	UserID      int64
	ServerState []byte
	ExpiresAt   time.Time
}

// CreatePendingLogin stores temporary OPAQUE login state.
func (q *Queries) CreatePendingLogin(ctx context.Context, arg CreatePendingLoginParams) error {
	_, err := q.db.ExecContext(ctx, createPendingLogin,
		arg.ID,
		arg.UserID,
		arg.ServerState,
		arg.ExpiresAt,
	)
	return err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :exec
INSERT INTO pending_registrations (
	id,
	username,
	username_normalized,
	server_state,
	expires_at
) VALUES (?, ?, ?, ?, ?)
`

type CreatePendingRegistrationParams struct {
	ID                 string
	Username           string
	UsernameNormalized string
	ServerState        []byte
	ExpiresAt          time.Time
}

// CreatePendingRegistration stores temporary OPAQUE registration state.
func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, createPendingRegistration,
		arg.ID,
		arg.Username,
		arg.UsernameNormalized,
		arg.ServerState,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
	username,
	username_normalized,
	opaque_registration_record
) VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Username                 string
	UsernameNormalized       string
	OpaqueRegistrationRecord []byte
}

// CreateUser registers a new OPAQUE user after registration has been completed.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.UsernameNormalized, arg.OpaqueRegistrationRecord)
	return err
}

const createVault = `-- name: CreateVault :exec
INSERT INTO vaults (
	user_id,
	encrypted_blob
) VALUES (?, ?)
`

type CreateVaultParams struct {
	UserID        int64
	EncryptedBlob []byte
}

// CreateVault initializes a user's encrypted vault.
func (q *Queries) CreateVault(ctx context.Context, arg CreateVaultParams) error {
	_, err := q.db.ExecContext(ctx, createVault, arg.UserID, arg.EncryptedBlob)
	return err
}

const deleteExpiredPendingLogins = `-- name: DeleteExpiredPendingLogins :exec
DELETE FROM pending_logins
WHERE expires_at <= CURRENT_TIMESTAMP
`

// DeleteExpiredPendingLogins removes expired OPAQUE login attempts.
func (q *Queries) DeleteExpiredPendingLogins(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPendingLogins)
	return err
}

const deleteExpiredPendingRegistrations = `-- name: DeleteExpiredPendingRegistrations :exec
DELETE FROM pending_registrations
WHERE expires_at <= CURRENT_TIMESTAMP
`

// DeleteExpiredPendingRegistrations removes expired OPAQUE registration attempts.
func (q *Queries) DeleteExpiredPendingRegistrations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPendingRegistrations)
	return err
}

const deletePendingLogin = `-- name: DeletePendingLogin :exec
DELETE FROM pending_logins
WHERE id = ?
`

// DeletePendingLogin removes pending OPAQUE login state after completion or cancellation.
func (q *Queries) DeletePendingLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePendingLogin, id)
	return err
}

const deletePendingLoginsByUserID = `-- name: DeletePendingLoginsByUserID :exec
DELETE FROM pending_logins
WHERE user_id = ?
`

// DeletePendingLoginsByUserID removes older pending login attempts for a user.
func (q *Queries) DeletePendingLoginsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deletePendingLoginsByUserID, userID)
	return err
}

const deletePendingRegistration = `-- name: DeletePendingRegistration :exec
DELETE FROM pending_registrations
WHERE id = ?
`

// DeletePendingRegistration removes pending OPAQUE registration state after completion or cancellation.
func (q *Queries) DeletePendingRegistration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePendingRegistration, id)
	return err
}

const deletePendingRegistrationsByUsernameNormalized = `-- name: DeletePendingRegistrationsByUsernameNormalized :exec
DELETE FROM pending_registrations
WHERE username_normalized = ?
`

// DeletePendingRegistrationsByUsernameNormalized removes older pending registration attempts for a username.
func (q *Queries) DeletePendingRegistrationsByUsernameNormalized(ctx context.Context, usernameNormalized string) error {
	_, err := q.db.ExecContext(ctx, deletePendingRegistrationsByUsernameNormalized, usernameNormalized)
	return err
}

const getPendingLogin = `-- name: GetPendingLogin :one
SELECT
	id,
	user_id,
	server_state,
	expires_at,
	created_at
FROM pending_logins
WHERE id = ?
LIMIT 1
`

// GetPendingLogin retrieves pending OPAQUE login state.
func (q *Queries) GetPendingLogin(ctx context.Context, id string) (PendingLogin, error) {
	row := q.db.QueryRowContext(ctx, getPendingLogin, id)
	var i PendingLogin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerState,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRegistration = `-- name: GetPendingRegistration :one
SELECT
	id,
	username,
	username_normalized,
	server_state,
	expires_at,
	created_at
FROM pending_registrations
WHERE id = ?
LIMIT 1
`

// GetPendingRegistration retrieves pending OPAQUE registration state.
func (q *Queries) GetPendingRegistration(ctx context.Context, id string) (PendingRegistration, error) {
	row := q.db.QueryRowContext(ctx, getPendingRegistration, id)
	var i PendingRegistration
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.ServerState,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
	id,
	username,
	username_normalized,
	crypto_policy_version,
	created_at,
	updated_at
FROM users
WHERE id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID                  int64
	Username            string
	UsernameNormalized  string
	CryptoPolicyVersion int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// GetUserByID retrieves a user by internal user ID.
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.CryptoPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameNormalized = `-- name: GetUserByUsernameNormalized :one
SELECT
	id,
	username,
	username_normalized,
	opaque_registration_record,
	crypto_policy_version,
	created_at,
	updated_at
FROM users
WHERE username_normalized = ?
LIMIT 1
`

// GetUserByUsernameNormalized retrieves a user by normalized username for OPAQUE login.
func (q *Queries) GetUserByUsernameNormalized(ctx context.Context, usernameNormalized string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameNormalized, usernameNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.OpaqueRegistrationRecord,
		&i.CryptoPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVaultByUserID = `-- name: GetVaultByUserID :one
SELECT
	encrypted_blob,
	revision,
	created_at,
	updated_at
FROM vaults
WHERE user_id = ?
LIMIT 1
`

type GetVaultByUserIDRow struct {
	EncryptedBlob []byte
	Revision      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// GetVaultByUserID fetches the encrypted vault blob and revision for a user.
func (q *Queries) GetVaultByUserID(ctx context.Context, userID int64) (GetVaultByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultByUserID, userID)
	var i GetVaultByUserIDRow
	err := row.Scan(
		&i.EncryptedBlob,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVaultIfRevisionMatches = `-- name: UpdateVaultIfRevisionMatches :execrows
UPDATE vaults
SET
	encrypted_blob = ?,
	revision = revision + 1,
	updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
AND revision = ?
`

type UpdateVaultIfRevisionMatchesParams struct {
	EncryptedBlob []byte
	UserID        int64
	Revision      int64
}

// UpdateVaultIfRevisionMatches updates a vault only if the expected revision matches.
func (q *Queries) UpdateVaultIfRevisionMatches(ctx context.Context, arg UpdateVaultIfRevisionMatchesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVaultIfRevisionMatches, arg.EncryptedBlob, arg.UserID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const usernameExists = `-- name: UsernameExists :one
SELECT COUNT(*) > 0 AS username_exists
FROM users
WHERE username_normalized = ?
`

// UsernameExists checks whether a normalized username is already registered.
func (q *Queries) UsernameExists(ctx context.Context, usernameNormalized string) (bool, error) {
	row := q.db.QueryRowContext(ctx, usernameExists, usernameNormalized)
	var username_exists bool
	err := row.Scan(&username_exists)
	return username_exists, err
}
